variables:
  ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
    PB_PublishBlobFeedKey:
    PB_PublishBlobFeedUrl:

phases:
- template: /eng/build.yml
  parameters:
    agentOs: Windows_NT
    queue:
      ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
        name: Hosted VS2017
      ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:        
        name: DotNetCore-Build
        demands:
        - agent.os -equals Windows_NT        
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _PublishType: none
          _SignType: test
        Build_Release:
          _BuildConfig: Release
          ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
            _PublishType: none
            _SignType: test
          ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
            _PublishType: blob
            _SignType: real


- template: /eng/build.yml
  parameters:
    agentOs: Linux
    dockerImage: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
    queue: 
      ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
        name: DotNetCore-Linux
      ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:        
        name: DotNetCore-Test
        demands:
          - agent.os -equals Linux
      parallel: 2
      matrix:
        Build_Debug:
          _BuildConfig: Debug
          _PublishType: none
          _SignType: test
        Build_Release:
          _BuildConfig: Release
          _PublishType: none
          ${{ if in(variables['Build.Reason'], 'PullRequest') }}:
            _SignType: test
          ${{ if notIn(variables['Build.Reason'], 'IndividualCI', 'BatchedCI') }}:
            _SignType: real

